# Generated by Django 3.1.13 on 2021-07-07 17:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vestaweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stormcell',
            name='Ipos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='Jpos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='adata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storm_cell', to='vestaweb.adaptationdata'),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='azimut',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='bases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='centroids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='forecast_Ipos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='forecast_Jpos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='maxZ',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='max_ref_hgts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='past_Ipos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='past_Jpos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='poh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='posh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='range',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='tops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='vil',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
