# Generated by Django 3.1.13 on 2021-07-07 18:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vestaweb', '0002_auto_20210707_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stormcell',
            name='Ipos',
        ),
        migrations.RemoveField(
            model_name='stormcell',
            name='Jpos',
        ),
        migrations.RemoveField(
            model_name='stormcell',
            name='forecast_Ipos',
        ),
        migrations.RemoveField(
            model_name='stormcell',
            name='forecast_Jpos',
        ),
        migrations.RemoveField(
            model_name='stormcell',
            name='past_Ipos',
        ),
        migrations.RemoveField(
            model_name='stormcell',
            name='past_Jpos',
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='adata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storm_cell', to='vestaweb.adaptationdata'),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='azimut',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='bases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='centroids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='maxZ',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='max_ref_hgts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='poh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='posh',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='range',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='tops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
        migrations.AlterField(
            model_name='stormcell',
            name='vil',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.CreateModel(
            name='StormTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('label', models.CharField(max_length=2)),
                ('Ipos', models.IntegerField()),
                ('Jpos', models.IntegerField()),
                ('past_Ipos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('past_Jpos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('forecast_Ipos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('forecast_Jpos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storm_tracking', to='vestaweb.radar')),
            ],
            options={
                'ordering': ('-created', 'radar', 'Ipos'),
            },
        ),
    ]
