# Generated by Django 3.1.13 on 2021-07-28 13:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vestaweb', '0003_auto_20210707_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='VWP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('hts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('u', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('v', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('w', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('rms', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('div', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('srng', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('elev', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vwp', to='vestaweb.radar')),
            ],
            options={
                'ordering': ('-created', 'radar'),
            },
        ),
    ]
