# Generated by Django 3.2.6 on 2021-08-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestaweb', '0005_vwp_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='stormcell',
            name='lst_vol_data_ptr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stormcell',
            name='lst_vol_time_ptr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
